name: CI Checks - Test, Format

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.17]
        otp: [27]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test

  credo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.17
          otp-version: 27

      - name: Install dependencies
        run: mix deps.get

      - name: Run Credo
        run: mix credo

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.17
          otp-version: 27

      - name: Install dependencies
        run: mix deps.get

      - name: Run Mix Format
        run: mix format

      - name: Commit format changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || git commit -am "Apply mix format"

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.17
          otp-version: 27

      - name: Install dependencies
        run: mix deps.get

      - name: Publish to HexDocs
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.docs
